### ISSUE TITLE
Los codigos QR estan invertidos (Solución propuesta)

### ISSUE THREAD

**Issue by danielr18** [Cuevana/storm#155]
Los codigos QR con el color blanco como el color oscuro no puede ser leido por todas las apps. Causando que uno tenga que ir probando distintas aplicaciones hasta que pueda ser leido.

El problema puede ser solucionado editando: storm/app/js/services/Remote.js

```
       generateCode: function() {
        // Remote QR Code
        qrcode = new QRCode('qr-code', {
            text: this.finalUrl(),
            width: 200,
            height: 200,
            colorDark : '#ffffff',
            colorLight : 'transparent',
            correctLevel : QRCode.CorrectLevel.L
        });
    },
```

Como pueden notar, estan utilizando como "colorDark" el color blanco. Lo mejor seria invertir los colorers, ya que el background siempre tiende a ser un poco oscuro.:

```
          generateCode: function() {
        // Remote QR Code
        qrcode = new QRCode('qr-code', {
            text: this.finalUrl(),
            width: 200,
            height: 200,
            colorDark : 'transparent',
            colorLight : '#ffffff',
            correctLevel : QRCode.CorrectLevel.L
        });
    },
```

Lo siguiente es editar el archivo: storm/app/assets/css/less.css

Sustituir: 

``` css
#qr-code {
  width: 200px;
  margin: 15px auto;
}
```

Por:

``` css
#qr-code {
  width: 200px;
  margin: 15px auto;
  border-style: solid;
  border-width: 5px;
  border-color: #ffffff;
}
```

Esto agrega un borde blanco alrededor del codigo QR.

Antes:

![original](https://cloud.githubusercontent.com/assets/9046616/4552289/788da5d6-4e80-11e4-99ab-4f360ad0651f.PNG)

Despues:

![fixed](https://cloud.githubusercontent.com/assets/9046616/4562285/56a1a26e-4f03-11e4-8be4-2f006c9c13e4.PNG)

El codigo QR es detectado inmediatamente con esta solución a diferencia del original.
